#pragma once

#define BOARD_NAME "AI Smart Collar V0 / ESP-WROOM-32"
#define BOARD_EXPECTED_IDF_TARGET "esp32"
#define BOARD_TRANSPORT_NAME "SPP"
#define BOARD_WIRELESS_DEVICE_NAME "SmartCollar-V0"
#define BOARD_SPP_SERVER_NAME "SmartCollar-V0"

#define BOARD_ECG_ADC_GPIO GPIO_NUM_34
#define BOARD_ECG_ADC_CHANNEL ADC_CHANNEL_6
#define BOARD_ECG_ADC1_CHANNEL 6U
#define BOARD_ECG_ADC_RAW_MAX 4095
#define BOARD_AD8232_LO_MINUS_GPIO GPIO_NUM_25
#define BOARD_AD8232_LO_PLUS_GPIO GPIO_NUM_26

#define BOARD_I2C_SDA_GPIO GPIO_NUM_21
#define BOARD_I2C_SCL_GPIO GPIO_NUM_22
