#pragma once

#include "driver/gpio.h"
#include "driver/i2c_types.h"
#include "esp_adc/adc_oneshot.h"
#include "sdkconfig.h"

#define BOARD_FIRMWARE_VERSION "0.2.0"

#if !CONFIG_IDF_TARGET_ESP32C3
#error "AI Smart Collar supports only the esp32c3 target"
#else
#include "board_esp32c3_supermini.h"
#endif

#define BOARD_FLASH_SIZE_MB 4U
#define BOARD_CONFIGURED_FLASH_SIZE_BYTES (BOARD_FLASH_SIZE_MB * 1024U * 1024U)
#define BOARD_FACTORY_APP_SIZE_BYTES (2U * 1024U * 1024U)

#define BOARD_ECG_SAMPLE_RATE_HZ 500U
#define BOARD_ECG_TIMER_PERIOD_US 2000U
#define BOARD_IMU_SAMPLE_RATE_HZ 50U
#define BOARD_OLED_REFRESH_RATE_HZ 2U
#define BOARD_OLED_REFRESH_INTERVAL_MS 1000U
#define BOARD_OLED_PAGE_INTERVAL_MS 3000U

#define BOARD_I2C_PORT I2C_NUM_0
#define BOARD_I2C_FREQUENCY_HZ (50U * 1000U)
#define BOARD_I2C_SCAN_FIRST_ADDR 0x08U
#define BOARD_I2C_SCAN_LAST_ADDR 0x77U
#define BOARD_I2C_SCAN_TIMEOUT_MS 50
#define BOARD_I2C_XFER_TIMEOUT_MS 200

#define BOARD_MPU6050_EXPECTED_ADDR 0x68U
#define BOARD_OLED_USUAL_ADDR 0x3CU
#define BOARD_OLED_WIDTH 128U
#define BOARD_OLED_HEIGHT 32U

#define BOARD_ECG_RING_CAPACITY 1024U
#define BOARD_IMU_RING_CAPACITY 128U
#define BOARD_TRANSPORT_TX_QUEUE_DEPTH 32U
#define BOARD_TRANSPORT_LOW_PRIORITY_QUEUE_DEPTH 8U
#define BOARD_TRANSPORT_MAX_FRAME_SIZE 256U

#define BOARD_ECG_TASK_PRIORITY 11U
#define BOARD_IMU_TASK_PRIORITY 8U
#define BOARD_PACKET_TASK_PRIORITY 7U
#define BOARD_TRANSPORT_TX_TASK_PRIORITY 6U
#define BOARD_VOICE_AUDIO_TASK_PRIORITY 9U
#define BOARD_MIC_WORKER_TASK_PRIORITY 5U
#define BOARD_OLED_TASK_PRIORITY 3U

#define BOARD_ECG_TASK_STACK_BYTES 4096U
#define BOARD_IMU_TASK_STACK_BYTES 4096U
#define BOARD_PACKET_TASK_STACK_BYTES 4096U
#define BOARD_TRANSPORT_TX_TASK_STACK_BYTES 4096U
#define BOARD_VOICE_AUDIO_TASK_STACK_BYTES 6144U
#define BOARD_MIC_WORKER_TASK_STACK_BYTES 6144U
#define BOARD_OLED_TASK_STACK_BYTES 4096U
